package com.example.kandraw.ui.customThemes

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

val deepSeaTheme: CustomTheme = CustomTheme(
    name = "DeepSea",
    lightColorScheme = ColorScheme(
        primary = Color(0xFF00696B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF5FF8FA),
        onPrimaryContainer = Color(0xFF002020),
        secondary = Color(0xFF00696B),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFF6FF6F8),
        onSecondaryContainer = Color(0xFF002020),
        tertiary = Color(0xFF006493),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCAE6FF),
        onTertiaryContainer = Color(0xFF001E30),
        error = Color(0xFFBA1A1A),
        errorContainer = Color(0xFFFFDAD6),
        onError = Color(0xFFFFFFFF),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFAFCFF),
        onBackground = Color(0xFF001F2A),
        surface = Color(0xFFFAFCFF),
        onSurface = Color(0xFF001F2A),
        surfaceVariant = Color(0xFFDAE5E4),
        onSurfaceVariant = Color(0xFF3F4948),
        outline = Color(0xFF6F7979),
        inverseOnSurface = Color(0xFFE1F4FF),
        inverseSurface = Color(0xFF003547),
        inversePrimary = Color(0xFF37DBDD),
        surfaceTint = Color(0xFF00696B),
        outlineVariant = Color(0xFFBEC8C8),
        scrim = Color(0xFF000000)
    ),
    darkColorScheme = ColorScheme(
        primary = Color(0xFF37DBDD),
        onPrimary = Color(0xFF003737),
        primaryContainer = Color(0xFF004F50),
        onPrimaryContainer = Color(0xFF5FF8FA),
        secondary = Color(0xFF4CDADC),
        onSecondary = Color(0xFF003738),
        secondaryContainer = Color(0xFF004F50),
        onSecondaryContainer = Color(0xFF6FF6F8),
        tertiary = Color(0xFF8DCDFF),
        onTertiary = Color(0xFF00344F),
        tertiaryContainer = Color(0xFF004B70),
        onTertiaryContainer = Color(0xFFCAE6FF),
        error = Color(0xFFFFB4AB),
        errorContainer = Color(0xFF93000A),
        onError = Color(0xFF690005),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF001F2A),
        onBackground = Color(0xFFBFE9FF),
        surface = Color(0xFF001F2A),
        onSurface = Color(0xFFBFE9FF),
        surfaceVariant = Color(0xFF3F4948),
        onSurfaceVariant = Color(0xFFBEC8C8),
        outline = Color(0xFF899392),
        inverseOnSurface = Color(0xFF001F2A),
        inverseSurface = Color(0xFFBFE9FF),
        inversePrimary = Color(0xFF00696B),
        surfaceTint = Color(0xFF37DBDD),
        outlineVariant = Color(0xFF3F4948),
        scrim = Color(0xFF000000)
    )
)

val filcTheme = CustomTheme(
    name = "Filc",
    lightColorScheme = ColorScheme(
        primary = Color(0xFF006B57),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF7DF8D6),
        onPrimaryContainer = Color(0xFF002019),
        secondary = Color(0xFF4B635B),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCDE9DE),
        onSecondaryContainer = Color(0xFF072019),
        tertiary = Color(0xFF006C47),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF80F9BD),
        onTertiaryContainer = Color(0xFF002113),
        error = Color(0xFFBA1A1A),
        errorContainer = Color(0xFFFFDAD6),
        onError = Color(0xFFFFFFFF),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFBFDFA),
        onBackground = Color(0xFF191C1B),
        surface = Color(0xFFFBFDFA),
        onSurface = Color(0xFF191C1B),
        surfaceVariant = Color(0xFFDBE5DF),
        onSurfaceVariant = Color(0xFF3F4945),
        outline = Color(0xFF6F7975),
        inverseOnSurface = Color(0xFFEFF1EE),
        inverseSurface = Color(0xFF2E312F),
        inversePrimary = Color(0xFF5FDBBA),
        surfaceTint = Color(0xFF006B57),
        outlineVariant = Color(0xFFBFC9C4),
        scrim = Color(0xFF000000)
    ),
    darkColorScheme = ColorScheme(
        primary = Color(0xFF5FDBBA),
        onPrimary = Color(0xFF00382C),
        primaryContainer = Color(0xFF005141),
        onPrimaryContainer = Color(0xFF7DF8D6),
        secondary = Color(0xFFB2CCC2),
        onSecondary = Color(0xFF1D352E),
        secondaryContainer = Color(0xFF344C44),
        onSecondaryContainer = Color(0xFFCDE9DE),
        tertiary = Color(0xFF62DCA3),
        onTertiary = Color(0xFF003823),
        tertiaryContainer = Color(0xFF005234),
        onTertiaryContainer = Color(0xFF80F9BD),
        error = Color(0xFFFFB4AB),
        errorContainer = Color(0xFF93000A),
        onError = Color(0xFF690005),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF191C1B),
        onBackground = Color(0xFFE1E3E0),
        surface = Color(0xFF191C1B),
        onSurface = Color(0xFFE1E3E0),
        surfaceVariant = Color(0xFF3F4945),
        onSurfaceVariant = Color(0xFFBFC9C4),
        outline = Color(0xFF89938E),
        inverseOnSurface = Color(0xFF191C1B),
        inverseSurface = Color(0xFFE1E3E0),
        inversePrimary = Color(0xFF006B57),
        surfaceTint = Color(0xFF5FDBBA),
        outlineVariant = Color(0xFF3F4945),
        scrim = Color(0xFF000000)
    )
)




